### ISSUE TITLE
Suggestion : Expose minishift cmds as REST endpoints

### ISSUE THREAD

**Issue by cmoulliard** [jimmidyson/minishift#96]
This could be interesting that we wrap the `minishift` commands around Rest endpoints (http://thenewstack.io/make-a-restful-json-api-go/). That could help us like also with the `oc` client to develop tools required for the developer

**Comment by rhuss** [comment]
Who would start a minishift daemon ? tbh, I don't think that makes much sense since the minishift commands are lifecycle commands, which would directly map to the lifecycle commands of a minishift daemon which would need to be started to provide this REST API.

Or they make only sense when called from the cli (like 'service', 'console' or 'ssh').

Everything else is covered by the OpenShift REST API which can be directly be used by tools like f-m-p.

**Comment by jimmidyson** [comment]
I agree with @rhuss, Minishift commands are just wrappers around the OpenShift/Kubernetes API. `oc` should just provide the same so it can provide the developer tooling required regardless of whether you're running minishift or a prod openshift cluster.

I'm going to close this but feel free to argue with me if you feel really strongly & can provide some concrete use cases :)
